### ISSUE TITLE
Directory structure confusion

### ISSUE THREAD

**Issue by StephanEggermont** [pharo-project/pharo-launcher#51] opened 2017-11-09 19:10 UTC
http://forum.world.st/PharoLauncher-directories-td5014383.html

In Pharo-users, I wrote:
I run into all kinds of issues with the directory structure used by the new PharoLauncher. pharo-local seems to be shared now for multiple images. That makes using configurations practically impossible as they are not expecting to have to deal with pre-downloaded older and newer monticello files. The missing sources files is less of a problem. 

--------------------
Guille responded with some details on the recent changes:
An analysis of the situation so people out of context can understand better the forces in play here :)

 - Working directory and files constant property: files defined using a *relative path* are created relative to the working directory.
    In other words: 
       File named: 'something/other/myfile.txt'
    will be created in FileSystem workingDirectory.
    This was always like this when we used the file primitives.
    The diverging behaviour was introduced actually by FileSystem: FileSystem used to create by default all files relative to the image directory. And at some point all tools adapted to that and the correct behaviour was hidden.

- Change in working directory: Before, pharo always satisfied the following property:
       FileSystem workingDirectory = FileSystem imageDirectory
  
   This is no longer true for every case.
   Now, the workingDirectory is aligned with the process' working directory (This is the equivalent to getcwd() in C, pwd command in linux, $PWD in bash).
   I explained a couple of weeks ago in an email, this may break some eggs, specially for those tools that wrongly assume FileSystem workingDirectory = FileSystem imageDirectory.
   Tools requiring imageDirectory should use imageDirectory explicit. At least that will keep backwards compatibility.
   For other cases, we should probably study them case by case and provide a satisfying solution.

   This change does however not affect everybody, and most of the times it is backwards compatible:

   ** This does not affect in general people launching usually pharo from the command line and using zeroconf:
       $ wget get.pharo.org/...
       $ ./pharo Pharo.image
       ## Here, FileSystem workingDirectory = FileSystem imageDirectory because I launched my image from the directory where my image is!

   ** This does affect people that are:
      - launching Pharo doing double click.
          In this case, we saw with Denis and Pavel a week ago that osx assigns as working directory the root directory "/"
          Users of files should be aware of this and applications should not abuse the workingDirectory. If they want to enforce the imageDirectory, they should do so explicitly.

     - launching Pharo from the pharo launcher (taken from this thread)
         Apparently the pharo launcher is launching the image from a directory internal to the launcher. This means that the working directory will be assigned to that directory. I'd expect that the directory structure is private to the launcher...
        I find even strange that the launcher puts pharo-local where the image is...
 

Given this, possible solutions are:
  - On fileout, chose a correct directory when launched from double click
  - Make the pharo launcher set a well-known working directory when launching an image
      - one possibility is to set $HOME
      - another possibility is to set the image directory (this will keep backwards compatibility)

@Stef: about the #fullname. It is not there because it is not implemented :). We did not have the possibility of calculating a correct full path until a couple of weeks ago (and before, even if we did so, it couldn't be done without introducing a dependency to a non-kernel package).
-------------
Christophe responded:
>      - launching Pharo from the pharo launcher (taken from this thread)
>          Apparently the pharo launcher is launching the image from a directory internal to the launcher.

In the Pharo launcher, I explicitly set the current working directory to the VM directory so that the VM can find its files.

> This means that the working directory will be assigned to that directory. I'd expect that the directory structure is private to the launcher...
>         I find even strange that the launcher puts pharo-local where the image is…

Pharo Launcher does not choose where to put pharo-local. It just stands in the standard place aside the launched image.

>  Given this, possible solutions are:
>   - On fileout, chose a correct directory when launched from double click
>   - Make the pharo launcher set a well-known working directory when launching an image
>       - one possibility is to set $HOME
>       - another possibility is to set the image directory (this will keep backwards compatibility)

I think the last solution: set the working directory to the image directory is the best option.
It will require to find another way to get the vm find its files (probably with LD_LIBRARY_PATH, do not know if it will be enough) and a lot of testing.

**Comment by stef** [comment] 2017-11-09 19:55
hey, the real stef here, i think you made a mistake and wanted to mention someone else and not summon me?

**Comment by Ducasse** [comment] 2017-11-09 20:00
No I'm the real stef :)

**Comment by demarey** [comment] 2017-11-21 14:06
To summarize, the issue is that PharoLauncher uses the vm directory of the VM used to launch an image as current working directory. Since latest pharo 7 alpha versions, working directory is not anymore the image  directory leading to store `pharo-local` directory under the current working directory. that is a problem because, with the launcher, the working directory is the same for all images using the same VM.

Solution: set image directory as image directory and set LD_LIBRARY_PATH on linux

**Comment by demarey** [comment] 2017-11-21 14:12
@StephanEggermont could you test if the latest version (of mcz, not yet a new config) is ok for you?
You can update your Launcher image directly from Monticello

**Comment by StephanEggermont** [comment] 2017-11-27 16:37
Sorry for the delay, I was very busy at work

**Comment by demarey** [comment] 2017-11-29 08:42
@StephanEggermont No problem. Just tell me if the fix is ok or not when you have to test

**Comment by StephanEggermont** [comment] 2017-11-29 10:13
I tried with PharoLauncher-Core-ChristopheDemarey.144 and opened the Monticello browser on a freshly downloaded P7 32-bit latest. Package cache in pharo-local is there still pointing at the location of the first compatible P7 image

**Comment by demarey** [comment] 2017-11-30 08:45
Within the same configuration as yours, I ran 
```Smalltalk
FileLocator workingDirectory fullName "'/Users/demarey/Documents/Pharo/images/70-latest-32'"
```
So, the current directory is right for this launched image.
If I open a monticello browser, the package cache is set to _/Users/demarey/Documents/Pharo/images/70-latest-32/pharo-local/package-cache_ that also looks good.
Do you have something in your configuration that could interfer with that?

**Comment by demarey** [comment] 2018-01-15 15:13
I will close this issue as the issue looks solved for me.
Feel free to re-open it if it does not work as expected.

**Closed by demarey** 2018-01-15 15:13 UTC
