### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by DamienCassou** [pharo-project/pharo-launcher#24] opened 2016-04-14 11:21 UTC
Some users would like the launcher to auto-update. I'm typically not in favor of such solutions because, for me, this is the responsibility of the operating system to update installed software. But, I'm not against either as soon as:
- someone else implements it
- there is a way to deactivate that in systems where this can't work (e.g., if the launcher is installed in a directory owned by root)

**Comment by demarey** [comment] 2018-01-05 15:32
duplicate of #3

**Closed by demarey** 2018-01-05 15:32 UTC
