### ISSUE TITLE
PharoLauncher (bleedingEdge & signed) doesn't work on Windows 10

### ISSUE THREAD

**Issue by bstjean** [pharo-project/pharo-launcher#92] opened 2018-04-16 16:50 UTC
Windows 10, French.

Downloaded PharoLauncher (the latest installer at http://files.pharo.org/pharo-launcher/win-alpha/, bleedingedge and signed).

Installed it without problem in the directory I wanted (as opposed to defaulting to my Documents folder as it was previously). I installed PL in a directory without "funky" characters.

But it bombs when PL (class PhLDirectoryBasedImageRepository) assumes my images are located in C:\Users\BenoîSt-Jean\Documents\Pharo\images

The path is not correctly encoded (the î) and it breaks.

No window opens, I get a blank screen and a debugger. 

Screenshot & fuel stack attached.
![pharolauncherbleedingedgelastinstaller](https://user-images.githubusercontent.com/17520767/38823397-544a04ea-4174-11e8-99ef-627d31c1fcf8.JPG)
[Debugger-Stack-WindowsStore-2018-04-16-12370.fuel.txt](https://github.com/pharo-project/pharo-launcher/files/1916356/Debugger-Stack-WindowsStore-2018-04-16-12370.fuel.txt)
[Debugger-Stack-WindowsStore-2018-04-16-12370.zip](https://github.com/pharo-project/pharo-launcher/files/1916364/Debugger-Stack-WindowsStore-2018-04-16-12370.zip)

**Comment by demarey** [comment] 2018-04-17 07:26
> Installed it without problem in the directory I wanted (as opposed to defaulting to my Documents folder as it was previously). I installed PL in a directory without "funky" characters.

I created a "Benoît" account on my windows VM and I was even not able to run the pharo VM. This issue is not specific to PL. I will see how to fix that.

> But it bombs when PL (class PhLDirectoryBasedImageRepository) assumes my images are located in C:\Users\BenoîSt-Jean\Documents\Pharo\images

> The path is not correctly encoded (the î) and it breaks.

> No window opens, I get a blank screen and a debugger. 

Thanks for the report. It will help to fix.

**Comment by svenvc** [comment] 2018-04-17 07:47
@demarey see my recent mails to to ML.

this is related to env vars decoding, I think

**Comment by demarey** [comment] 2018-04-17 08:04
@svenvc Yes, you're right.
I tested with a fresh Pharo 6.1 image and I got an error when Pharo tried to resolve HOME env variable. It can be reproduced with: `FilePathEncoder decode: 'C:\Users\benoît'` Encoding is assumed to be UTF8

**Comment by demarey** [comment] 2018-10-18 12:49
The latest Pharo version now manages better the encoding: http://files.pharo.org/pharo-launcher/1.4.6
However, there is still a limitation on Windows because the library used to fork processes and launch images uses an old API that does not deal with Unicode. A work around is to put the VM store and the image store in a path only containing ASCII characters.
I will close the issue because we cannot do more for now.

**Closed by demarey** 2018-10-18 12:49 UTC
