### ISSUE TITLE
GUI bug makes Launcher unusable

### ISSUE THREAD

**Issue by apblack** [pharo-project/pharo-launcher#104] opened 2018-05-23 05:37 UTC
I just downloaded a new version of the Launcher*, because I'm writing some instructions to help a neophyte get started.

When I right-click on one of the templates, I get:

![screen shot 2018-05-22 at 22 16 42](https://user-images.githubusercontent.com/410893/40404666-e40298b2-5e0d-11e8-871a-cff71f5f61e5.png)

For a novice, this is an absolute show-stopper.  I think that it's a bug in Spec, which causes orphaned morphs to hang around — see Issue https://pharo.fogbugz.com/f/cases/20811/TreePresenter-selection-issue-when-tree-is-collapsed

Note that this bug is _intermittent_; I think that it occurs when a morph is waiting to be GC'd, is no longer in a containing morph, but is still registered to respond to mouse events.

According to FogBugz, the fix for this bug was integrated into Pharo 7 on 5th March 2018.  However, the same method in the Launcher does not show the fix:

```
selected: aBoolean
	selected = aBoolean
		ifTrue: [^ self].
	aBoolean
		ifTrue: [container selectedMorphList add: self]
		ifFalse: [selected 
			ifNotNil: [container selectedMorphList remove: self]].
	selected := aBoolean.

	self complexContents selected: aBoolean
```

The patch is to put `container ifNil: [ ^ self ].` between lines 3 and 4, but the real fix would be to re-build the Launcher with a more-recent version of Pharo.

The "About" box on my version of the launcher says:

> Pharo Launcher version: 1.1
> Packages :
> - PharoLauncher-Core-ChristopheDemarey.169
> - PharoLauncher-Spec-ChristopheDemarey.64
> - PharoLauncher-Tests-Core-ChristopheDemarey.23
>

**Comment by demarey** [comment] 2018-05-23 16:06
Hi Andrew,

Thanks a lot for this report and a way to avoid it.
We planned to switch from MorphTreeMorph to FastTable but it takes time.
I just included your fix in the Launcher image:
```
Name: PharoLauncher-Spec-ChristopheDemarey.67
Author: ChristopheDemarey
Time: 23 May 2018, 6:01:53.405912 pm
UUID: 822eef63-4329-0d00-901a-a72302d5877a
Ancestors: PharoLauncher-Spec-ChristopheDemarey.66

include a fix for morphtreemorph bug.
see https://github.com/pharo-project/pharo-launcher/issues/41
```
It will be included in next Pharo Launcher release.

**Comment by demarey** [comment] 2018-05-23 16:09
duplicate of #41

**Closed by demarey** 2018-05-23 16:09 UTC
