### ISSUE TITLE
Pharo Launcher on Windows giving error when selecting an entry in the left tree list

### ISSUE THREAD

**Issue by philippeback** [pharo-project/pharo-launcher#90] opened 2018-04-14 14:55 UTC
![image](https://user-images.githubusercontent.com/2128441/38769496-5e79e12c-4004-11e8-8925-2081628b7af8.png)

FueledOut stack

[Debugger-Stack-UndefinedObject-2018-04-14-165350.zip](https://github.com/pharo-project/pharo-launcher/files/1910501/Debugger-Stack-UndefinedObject-2018-04-14-165350.zip)

**Comment by demarey** [comment] 2018-04-17 06:57
Thanks for the report.
I think you do not always have it but it is annoying.
Duplicate of #41

**Comment by demarey** [comment] 2018-05-30 08:02
should now be fixed

**Closed by demarey** 2018-05-30 08:02 UTC
