### ISSUE TITLE
#, was sent to nil

### ISSUE THREAD

**Issue by bpieber** [pharo-project/pharo-launcher#56] opened 2017-12-02 15:40 UTC
Here is what I did (I am on macOS Sierra):
1. I deleted my Pharo Launcher from Applications.
2. I downloaded http://files.pharo.org/platform/launcher/Pharo_1.0.1.dmg.
3. I mounted the disk image file.
4. I copied Pharo.app to Applications.
5. I started Pharo.app.
6. I expanded the Local folder.
7. I selected latest.
8. I clicked on the Create image button and chose the name latest.
9. I selected latest in the Existing images list.
10. I clicked the Launch button.
11. A debugger opens: UndefinedObject dNU: #,

**Comment by demarey** [comment] 2017-12-04 09:35
Hi Bernahrd,

Thanks for the report.
First of all, files under the local directory are dependent of your usage of the Pharo Launcher. If you never used Pharo Launcher, the only entry sowing up in the local category is `Pharo image (stable)`. Just to say, that I'm not able to reproduce exactly what you did because I do not know to which image _latest_ refers to.

I tried with `Pharo image (stable)` and was not able to reproduce the problem.
That said, this problems comes when the launcher failed to find the Pharo image version of an image. I need to catch the error and provide a better message.
What you could do is to log the command run by the launcher in `PhLImage>>#launchCommandWith:` and try to run it in a shell to see what happens.

**Comment by bpieber** [comment] 2017-12-05 07:12
Hi Christophe,

So where do the entries in the Local list come from then? Where are they stored? Is there a way to reset it to factory settings? Refresh template list doesn't. I must admit that I still don't understand that list. When do entries get added to the Local list?

Here is the command:
cd "/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS" && "/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Pharo" --headless "/Users/bernhard/Documents/Pharo/images/latest/latest.image" --no-default-preferences eval "(Smalltalk imagePath asFileReference parent) / 'pharo.version' 
		writeStreamDo: [ :stream | |major minor|
			major := SystemVersion current major.
			minor := SystemVersion current minor.
			(major = 6 and: [ SystemVersion current highestUpdate >= 60509 ])
				ifTrue: [ minor := 1 ].
			stream 
				<< major asString;
				<< minor asString ]"

I tried to run it by pasting it to a terminal, but it filled the terminal with file listings. When I removed the linefeeds from the command I got the following errors:

2017-12-05 08:09:35.805 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LocalePlugin'
2017-12-05 08:09:35.806 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.807 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.807 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.811 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.811 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.814 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.815 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.815 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.817 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.818 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.818 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.819 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.820 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.820 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/FilePlugin'
2017-12-05 08:09:35.823 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/FilePlugin'
2017-12-05 08:09:35.824 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/InternetConfigPlugin'
2017-12-05 08:09:35.825 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/FilePlugin'
2017-12-05 08:09:35.828 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/FilePlugin'
2017-12-05 08:09:35.829 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/FilePlugin'
2017-12-05 08:09:35.850 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/FilePlugin'
2017-12-05 08:09:35.924 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/MiscPrimitivePlugin'
2017-12-05 08:09:35.926 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/ZipPlugin'
2017-12-05 08:09:35.926 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/ZipPlugin'
2017-12-05 08:09:35.927 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.927 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/LargeIntegers'
2017-12-05 08:09:35.929 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/ZipPlugin'
2017-12-05 08:09:35.934 Pharo[34681:506909] *** -[NSPathStore2 stringByAppendingPathExtension:]: cannot append extension 'bundle/Contents/MacOS/' to path '/Users/bernhard/Documents/Pharo/vms/private/6505/Pharo.app/Contents/MacOS/Plugins/ZipPlugin'

**Comment by demarey** [comment] 2017-12-05 08:08
Hi Bernahrd,

Templates under the local category has only one entry with a fresh install: the latest stable Pharo image shipped with the Launcher. It gets populated once you start to download images from internet (I.e. any other category in Pharo Launcher). Local templates are stored in `FileLocator preferences / 'pharo' / 'templateCache'`. There is currently no way to clean it from the Launcher interface. You could just clean the folder (and maybe the ston file).
When I copy/paste the command in my terminal (and replacing vm and image patch with one I have on my laptop), it works. Could you try to reproduce the problem with a Pharo image you know the version? This way, I will try to reproduce it (I use El Capitan but I could ask someone else to try)

**Comment by bpieber** [comment] 2017-12-05 16:11
Thanks for the explanation. I can only remember getting this error with the "latest" image, so I am not sure I can reproduce it with another image. I will try.

**Comment by bpieber** [comment] 2017-12-05 18:39
After a bit of detective work I found out that the image in question is a 4.0 image, http://files.pharo.org/image/40/40621.zip to be precise, albeit named latest. The debugger can be reproduced by creating an image from Deprecated distributions > Pharo 4.0 and launching it.

How I got the Local > latest.image? Most probably it is an ancient remnant from an older Pharo Launcher installation? If yes, a possibility to remove images from the local templates seems in order.

**Comment by demarey** [comment] 2018-01-04 16:00
I just published a new code handling this error and displaying the command the Pharo Launcher tried to use.
You can try [this new version ](http://files.pharo.org/pharo-launcher/bleedingEdge/) and open a new issue if you still have problems. 
I will close this one as `#, was sent to nil` is now handled.

**Closed by demarey** 2018-01-04 16:00 UTC
