### ISSUE TITLE
Ctrl+Shift+Right in Spotter doesn't work as intended

### ISSUE THREAD

**Issue by readyready15728** [pharo-project/pharo-launcher#519] opened 2021-03-28 13:00 UTC
**Describe the bug**
Spotter suggests the use of Ctrl+Shift+Right to see full results for a given search. What this does instead is produce an extended menu and, so far, only double-clicking has actually worked. The behavior appears on Pharo 8.0 and 9.0 as well.

**To Reproduce**
1. Open Spotter
2. Do a search with lots of results
3. Attempt to follow instructions on arrow

**Expected behavior**
Full results to appear when using suggested keys, advice to use double-click instead, or perhaps a more intuitive (IMO) single-click functionality.

**Screenshots**
![screenshot](https://i.imgur.com/5ZxMs0q.png)

**Version information:**
- Ubuntu 20.04 (not likely the problem)
- Pharo 8.0 and 9.0

**Expected development cost**
Very small

**Additional context**
N/A

**Comment by Ducasse** [comment] 2021-03-29 07:24
Thanks for the report. 
We will remove this implementation of Spotter in P9. It will happen quit soon now.

**Comment by readyready15728** [comment] 2021-03-29 19:36
_Merci beaucoup!_

**Comment by demarey** [comment] 2022-03-31 08:17
I close the issue since Spotter has been replaced and the issue is not related to Pharo Launcher but Pharo.

**Closed as completed by demarey** 2022-03-31 08:17 UTC
Labels: Bug
