### ISSUE TITLE
Quick left-click then right-click on an image opens it instead of showing the contextual menu

### ISSUE THREAD

**Issue by dupriezt** [pharo-project/pharo-launcher#296] opened 2019-01-25 12:43 UTC
Left-click then quick right-click on an image launches it as if a double left-click had been made.
This is annoying when wanting to select an image (left-click) and open a contextual menu on it (right-click): if the two clicks are too close to each other temporally, it launches the image instead of opening the contextual menu.

**Comment by demarey** [comment] 2019-01-31 11:08
I cannot reproduce it on my laptop.
Nevertheless, it is not an issue that PharoLauncher can address. It is related to mouse event management (emulation) done by the VM.
I will close this bug but if you can reproduce such behaviour on other Pharo tools, feel free to open a bug entry to Pharo issue tracker.

**Closed as completed by demarey** 2019-01-31 11:08 UTC
