### ISSUE TITLE
Closing the PharoLauncher image closes all the images it launched

### ISSUE THREAD

**Issue by dupriezt** [pharo-project/pharo-launcher#45] opened 2017-10-16 12:12 UTC
Linux Ubuntu 16.04 LTS
On latest-linux.zip from https://ci.inria.fr/pharo/view/Launcher/job/Publish-Launcher-stable-Linux/ (build #53)

After running the PharoLauncher and launching a few images with it, if I close the PharoLauncher image, all the other images are killed without save prompts.

And if the "Quit on launch" setting is on, whenever PharoLauncher launches an image, it quits itself, which closes the image just launched. Since "Quit on launch" is on by default, PharoLauncher looks like it doesn't work by default.

**Comment by demarey** [comment] 2018-01-10 07:17
duplicate of #61

**Closed by demarey** 2018-01-10 07:17 UTC
