### ISSUE TITLE
Pharo image won't launch and doesn't give an error

### ISSUE THREAD

**Issue by gregaz** [pharo-project/pharo-launcher#639] opened 2023-12-12 00:32 UTC
**Describe the bug**
I saved my Advent of Code image, closed it, and tried to relaunch and it fails to relaunch silently.

**To Reproduce**
Not sure, image must be corrupted, but it doesn't give an error when I attempt to launch. Copies of the image won't launch either.

**Expected behavior**
The image launches or gives an error why it doesn't launch.

**Screenshots**

**Version information:**
 - OS: Windows
 - Version: Pharo 11.0 64bit (stable)

**Expected development cost**
No idea

**Additional context**
I was able to recover my changes from the change files, but the corrupted image still doesn't launch and doesn't give an indication of why it doesn't launch.

**Comment by Ducasse** [comment] 2023-12-12 07:48
You can still rescue all your code so do not throw away your folder.
OK I saw that you did not lose your code.

**Comment by Ducasse** [comment] 2023-12-12 07:49
This is difficult for us to know what is happening. Could you reproduce this behavior?

**Comment by gregaz** [comment] 2023-12-12 13:15
I can reproduce it with my image file, but Github doesn't seem to allow me to add a file over 25 mb here, and it is 34 mb compressed. Is there a better way for me to share an image?

**Comment by guillep** [comment] 2023-12-12 13:17
There is the french state file sender utility that you could try? https://filesender.renater.fr/

<blockquote><div><strong><a href="https://filesender.renater.fr/">FileSender</a></strong></div></blockquote>

**Comment by gregaz** [comment] 2023-12-12 13:26
Looks like you need to be affiliated with a French educational organization to use that site, but I'm not from France :(

**Comment by gregaz** [comment] 2023-12-12 13:29
[Advent Of Code 2023 -  ded.txt](https://github.com/pharo-project/pharo-launcher/files/13648632/Advent.Of.Code.2023.-.ded.txt)
Winrar actually got it small enough hah! I attached the image file compressed as a .rar, but I had to rename it to .txt because Github doesn't allow .rar files :/

**Comment by demarey** [comment] 2023-12-14 14:34
Indeed, it looks like your image is corrupted.
Trying to run the image from the terminal gives this error:
```bash
 ~/Documents/Pharo/vms/110-x64/Pharo.app/Contents/MacOS/Pharo `Advent Of Code 2023 -  ded.image`
[ERROR] 2023-12-14 15:31:20.000 basicImageFileRead (src/imageAccess.c:92):fread: Invalid argument
[ERROR] 2023-12-14 15:31:20.000 error (src/debug.c:45):Read failed or premature end of image file

VM Error Thu Dec 14 15:31:20 2023
```

You can try in a cmd.exe terminal on windows to see if you have the same error.

For now, it is difficult for Pharo Launcher to get errors in launched images because a process is spawn and Pharo Launcher does not listen to it to get outputs.

**Comment by gregaz** [comment] 2023-12-16 17:33
Gotcha, thanks for looking into this and appreciate everyone supporting this project :) This would be a feature request to have the Pharo Launcher show errors, I was confused by the silent failures.

**Comment by demarey** [comment] 2024-01-12 13:56
I will close the issue as it is not possible for now to implement the feature for getting back errors from a spawned process.

**Closed as completed by demarey** 2024-01-12 13:56 UTC
Labels: Bug
