### ISSUE TITLE
Cannot find VM for any new Pharo 6 image

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-project/pharo-launcher#309] opened 2019-02-08 13:34 UTC
Whenever I create new image of Pharo 6.1 (32bit or 64bit, "latest", numbered or the one in "Official distributions"), Launcher cannot detect which VM it should open/download.

Steps to reproduce:
- Double click and name any Pharo 6(.1) image to download it
- Double click that new create image to open it
Launcher first shows "Determining image version" for a minute or so, then it shows error 

_Cannot determine image version
pharo.version file was not found for your image, and probably your VMs are not up to date. Please, contact us at http://pharo.org/community_

Tried reinstalling Launcher (and removing whole directory of Launcher) and removing vms directory in Documents. Using Windows 10 64bit.

**Comment by demarey** [comment] 2019-02-08 14:23
Hi Jan,

Thank you  for the report.
Could you try to put a breakpoint in `PhLProcessWrapper class>>#windowsCommand:` ?
(you can use shorcuts to open spotter or a browser in PharoLauncher)
Once done, try to launch you Pharo 6.1 image, open the debugger, copy the value of the command and try to execute in a command shell to see the output. An error probably occurred but we do not have the information.

**Comment by JanBliznicenko** [comment] 2019-02-08 15:06
Hi, thanks for your time.

When I put breakpoint (halt) to the beginning of the method and try to launch the image, it (the halt) never occurs.
But it seems that pharo.version does not get created in the first place (should have looked as a first thing) when I create any other image than Pharo 7. Pharo 6 does not get created with it, neither Pharo 5, 4... but Pharo 7 does and it works fine for Pharo 7.
Antivirus is off. I am not sure whether it stopped working when I updated Launcher, "by itself" (because of something happened at my PC) or when Pharo 7 got released, because last two weeks I was using only already existing images. Until now.

**Comment by demarey** [comment] 2019-02-08 15:11
ok, so please put a halt in `PhLProcessWrapper class>>#waitForWindowsCommand:` and try to execute the command in a shell

**Comment by JanBliznicenko** [comment] 2019-02-08 15:16
Command is
`cd "C:\Users\Honza\Pharo\vms\private\6521" && "C:\Users\Honza\Pharo\vms\private\6521\Pharo.exe" --headless "C:\Users\Honza\Pharo\images\Pharo 6.1 - 32bit (stable)\Pharo 6.1 - 32bit (stable).image" C:\Users\Honza\Pharo\pharo-version.st`
and when I execute it in command line, it just switches current directory and then seems not to do anything (executing the command ends almost immediately and nothing opens).

**Comment by JanBliznicenko** [comment] 2019-02-08 15:26
I updated Launcher in my laptop from 1.5.1 to current one and have the same problem there (was ok before). The laptop has, however, very similar configuration of SW as desktop PC.

**Comment by demarey** [comment] 2019-02-08 16:37
ok, the problem is there. 
What if you remove the headless flag? Do you see something useful?
Could you also try to add the `--no-default-preferences` flag?

**Comment by JanBliznicenko** [comment] 2019-02-09 22:29
Removing the headless flag causes opening file dialog for picking image file. Should the flag be replaced by other one instead?
Adding --no-default-preferences does not seem to change anything.
Also on my laptop the problem changed today (apparently by itself) - it's "determining image version" for like 3 minutes and then the image opens fine. On desktop, the problem is still the same (after half a minute "cannot determine image version").

**Comment by JanBliznicenko** [comment] 2019-02-09 22:34
When I open the image without using Launcher, copy the content of pharo-version.st and run it in Playground, it creates the pharo.version file fine, immediately and then the Launcher can open it without any problem. Copying content of pharo-version.st into exec parameter with headless flag causes same problem as running from Launcher.

**Comment by demarey** [comment] 2019-02-11 09:55
From what I see, there was one bug (see #284) that is now fixed. It could causs problem if you defined global settings for Pharo.
In your case, it does not look like it is the problem. When you remove the headless flag, the image should start. If it does not, it means Pharo cannot locate your image `"C:\Users\Honza\Pharo\images\Pharo 6.1 - 32bit (stable)\Pharo 6.1 - 32bit (stable).image"`. If you do a `dir "C:\Users\Honza\Pharo\images\Pharo 6.1 - 32bit (stable)\Pharo 6.1 - 32bit (stable).image"`, is it working?

**Comment by JanBliznicenko** [comment] 2019-02-11 10:27
Following your mention of bug #284, I think I got closer to the issue.
Removing startup.st from C:\Users\Honza\AppData\Roaming\pharo does help with the issue.
Specifically, removing Iceberg update from the startup.st.

It is still just hotfix for me, because I would like to have Iceberg updating in Pharo 6 automatically.

It seems the startup script is executed in current launcher when image is started in order to create pharo.version, although it didn't in older launchers (and probably shouldn't even in current one?). I made sure that's the case by adding line that creates new 'hello.txt' file at the beginning of startup.st, and it was indeed created while launcher was waiting for version info.

In the Iceberg update code I check if it is not already up to date - that's why images of Pharo 7 and 8 work fine and 6- don't.

**Comment by demarey** [comment] 2019-02-11 10:48
That's why image version determination should not use preferences. To avoid such kind of problems. It does not mean that your preferences will not be run at image launch but only to determine the Pharo version of your image. If you apply changes from https://github.com/pharo-project/pharo-launcher/pull/285/files to your Pharo Launcher, is it working fine (even with your startup.st script)?

**Comment by JanBliznicenko** [comment] 2019-02-11 11:36
Yes, applying these changes fixed the issue, thank you.

**Closed as completed** 2019-02-11 11:47 UTC
