### ISSUE TITLE
Double click on an existing image open a file selector

### ISSUE THREAD

**Issue by SergeStinckwich** [pharo-project/pharo-launcher#85] opened 2018-04-06 16:56 UTC
To reproduce the bug:
- select an image in the list of existing images
- double click on it, open a file selector

**Comment by demarey** [comment] 2018-04-06 18:51
Hi Serge,

This problem is caused by the poor moose event available in MorphTreeMorph. double-click is emulated: clic + another clic.
In your case: first click unselect the image and second click triggers the double click event => no image selected => Pharo Launcher ask you if you want to open an image from the filesystem.
If no image selected, first click select the image and second click triggers double-click event => Pharo Launcher launchs the selected image.

Maybe I should add a button in the toolbar to open an image from the file system and disable double-click action when no image selected?

**Comment by demarey** [comment] 2018-04-10 06:44
fixed in bleeding edge:
```
Name: PharoLauncher-Core-ChristopheDemarey.182
Author: ChristopheDemarey
Time: 9 April 2018, 2:04:31.692211 pm
UUID: 3b5f0bf2-ca25-0d00-9491-2e92058b48e2
Ancestors: PharoLauncher-Core-ChristopheDemarey.181

disable launch when no selection.
Import button now asks to launch or to import an image from disk.
```

**Closed by demarey** 2018-04-10 06:44 UTC
Labels: bug
