### ISSUE TITLE
Pharo Launcher 3.0.1 does not open on Windows 10

### ISSUE THREAD

**Issue by Shaping** [pharo-project/pharo-launcher#579] opened 2022-08-03 11:00 UTC
Pharo Laucher version: 3.0.1
OS: Windows 10 Pro

Pharo Launcher 3.0.1 still does not open on Windows 10 reliably.

I discussed this in the Discord.  There, John Brant reported that one of his Windows machines could open the PL and that a second machine could not.  The one that could not seemed to be missing the SDL DLL.  

My Windows machine cannot open PL 3.0.1, and the SDL DLL is present.  Every time I double click the PL icon, a new PL VM appears in TaskMan, but no GUI appears.   I installed in the default directory.

**Comment by demarey** [comment] 2022-09-20 07:35
Hi Shaping,

I'm not able to reproduce the problem on my Windows 10 virtual image.
Could you try to uninstall pharo launcher (ensure all files are deleted in your user folder>\AppData\Local\"Pharo Launcher" ) ?
Additionaly, can you send the output of `systeminfo` command and the path where is installed Pharo Launcher?

Thanks

**Comment by demarey** [comment] 2023-03-02 14:55
I'm closing the issue since I miss input to work on it but do not hesitate to reopen it.

**Closed as completed by demarey** 2023-03-02 14:55 UTC
Labels: Bug
