### ISSUE TITLE
Can not load script on mac

### ISSUE THREAD

**Issue by akevalion** [pharo-project/pharo-launcher#474] opened 2020-05-08 00:49 UTC
**Describe the bug**

In PL when I am creating a new image with the new initialization script I can not access to the scripts.

**To Reproduce**
1. Go to Pharo Launcher click on new.
2. A window template will appear
3. Go to the initialization scripts section, and click on the button to edit scripts.
![image](https://user-images.githubusercontent.com/10532890/81358246-f56f4300-90a3-11ea-92db-136daadaaf00.png)
4. This will add a new script available in your hard disk
![image](https://user-images.githubusercontent.com/10532890/81358270-08821300-90a4-11ea-9351-d08e30e91570.png)
5. But PL template can not read these files.
![image](https://user-images.githubusercontent.com/10532890/81358291-1a63b600-90a4-11ea-83a7-228084c3792e.png)

**Expected behavior**

PL should show Script templates

**Version information:**
 - OS: mac Catina 
 - Version: 10.15.3

**Comment by demarey** [comment] 2020-05-09 21:56
Hi Milton,

Thanks for the report.
The problem is a missing check for the `st` extension. Just add `.st` to your scripts and it should work fine.
It is fixed in the dev branch. See 2b01bfd

**Closed as completed by demarey** 2020-05-09 21:56 UTC
Labels: Bug
