### ISSUE TITLE
`[Post-mortem] PrimitiveFailed: primitive #primLoadSymbol:module: in TFFIBackend failed` upon enabling development environment

### ISSUE THREAD

**Issue by capsulecorplab** [pharo-project/pharo-launcher#584] opened 2022-12-20 20:24 UTC
**Describe the bug**
`[Post-mortem] PrimitiveFailed: primitive #primLoadSymbol:module: in TFFIBackend failed` error encountered after checking "Enable development environment" under "Pharo Launcher" in settings

**To Reproduce**
1. Go to Settings > Pharo Launcher
2. Click on checkbox next to "Enable development environment"
3. See error

**Expected behavior**

**Screenshots**
![Screenshot_20221217_155737](https://user-images.githubusercontent.com/14095576/208757443-623f09ed-48ce-476b-a419-527cf3deb8c6.png)

**Version information:**
 - OS: openSUSE Leap 15.4
 - Version: 3.0.1-x64

**Expected development cost**
Seems to be an issue with libgit.

**Additional context**
Enabling development environment was suggested as a fix to #128.

**Comment by demarey** [comment] 2023-01-27 15:02
You probably get this error because a library needed by libgit does not have the same name as the expected one. You can see similar issues in https://github.com/pharo-project/pharo/issues/4463
In the future, we would like to distribute pharo launcher as a linux package to avoid these problems.

**Comment by demarey** [comment] 2023-03-02 14:52
I will close the issue as it is not a bug that can be solved quickly but rather a packaging problem that should require a lot more work: packages created with OBS (like https://build.opensuse.org/project/subprojects/devel:languages:pharo)

<blockquote><img src="https://build.opensuse.org/assets/obs-logo_meta-0cc940130a6cceea822bfa0c5eaf466d900a2ed4df7eb7fe6936a24b188852ff.png" width="48" align="right"><div><img src="/assets/favicon-ac48595b97f38c2425d7ea77739a63d771fcda9f73cc8c474b66461c0836fc2a.ico" height="14"> openSUSE Build Service</div><div><strong><a href="https://build.opensuse.org/project/subprojects/devel:languages:pharo">openSUSE Build Service</a></strong></div></blockquote>

**Closed as completed by demarey** 2023-03-02 14:52 UTC
Labels: Bug
